In [4]:
import numpy as np

In [5]:
l = [1,2,3,4]

In [7]:
a = np.array(l)

In [9]:
a[0] = 5

In [10]:
a

array([5, 2, 3, 4])

In [11]:
a + 1

array([6, 3, 4, 5])

In [19]:
b = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
b.dtype

dtype('int32')

In [22]:
b[0]

array([1, 2, 3, 4])

In [23]:
b[0][0]

1

In [30]:
#第一个代表行，第二个代表列，然后第一个冒号代表取值范围，第二个冒号代表取值间隔。
b[0:,::2]

array([[ 1,  3],
       [ 5,  7],
       [ 9, 11]])

In [26]:
b.shape

(3, 4)